"""Portable Python File Commander.

Generated from the pycommander package. Requires only Python 3.10+ with Tk.
Do not edit this file directly; run tools/build_single_file.py after source changes.
"""

from __future__ import annotations

import os
import shutil
import ctypes
from pathlib import Path


def copy_items(items: list[Path], destination: Path) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    for source in items:
        target = destination / source.name
        if source.is_dir():
            shutil.copytree(source, target, dirs_exist_ok=True)
        else:
            shutil.copy2(source, target)


def move_items(items: list[Path], destination: Path) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    for source in items:
        shutil.move(str(source), str(destination / source.name))


def delete_items(items: list[Path]) -> None:
    for item in items:
        if item.is_dir() and not item.is_symlink():
            shutil.rmtree(item)
        else:
            item.unlink()


def format_size(size: int) -> str:
    value = float(size)
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if value < 1024 or unit == "TB":
            return f"{value:.0f} {unit}" if unit == "B" else f"{value:.1f} {unit}"
        value /= 1024
    return str(size)


def roots() -> list[Path]:
    if os.name != "nt":
        return [Path("/")]
    return [Path(f"{letter}:\\") for letter in "ABCDEFGHIJKLMNOPQRSTUVWXYZ" if Path(f"{letter}:\\").exists()]


def is_system(path: Path) -> bool:
    """Return whether Windows marks a path with the SYSTEM attribute."""
    if os.name != "nt":
        return False
    attributes = ctypes.windll.kernel32.GetFileAttributesW(str(path))
    return attributes != 0xFFFFFFFF and bool(attributes & 0x4)


import base64
import binascii
import ctypes
import os
import struct
import zlib
from pathlib import Path
from tkinter import PhotoImage


class _SHFILEINFO(ctypes.Structure):
    _fields_ = [("hIcon", ctypes.c_void_p), ("iIcon", ctypes.c_int),
                ("dwAttributes", ctypes.c_uint32), ("szDisplayName", ctypes.c_wchar * 260),
                ("szTypeName", ctypes.c_wchar * 80)]


class _BITMAPINFOHEADER(ctypes.Structure):
    _fields_ = [("biSize", ctypes.c_uint32), ("biWidth", ctypes.c_long),
                ("biHeight", ctypes.c_long), ("biPlanes", ctypes.c_ushort),
                ("biBitCount", ctypes.c_ushort), ("biCompression", ctypes.c_uint32),
                ("biSizeImage", ctypes.c_uint32), ("biXPelsPerMeter", ctypes.c_long),
                ("biYPelsPerMeter", ctypes.c_long), ("biClrUsed", ctypes.c_uint32),
                ("biClrImportant", ctypes.c_uint32)]


class _BITMAPINFO(ctypes.Structure):
    _fields_ = [("bmiHeader", _BITMAPINFOHEADER), ("bmiColors", ctypes.c_uint32 * 3)]


def _chunk(kind: bytes, data: bytes) -> bytes:
    return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", binascii.crc32(kind + data) & 0xFFFFFFFF)


def _png_from_bgra(raw: bytes, size: int) -> bytes:
    rgba = bytearray()
    has_alpha = any(raw[index + 3] for index in range(0, len(raw), 4))
    for row in range(size):
        rgba.append(0)
        for column in range(size):
            index = (row * size + column) * 4
            blue, green, red, alpha = raw[index:index + 4]
            if not has_alpha:
                alpha = 255 if red or green or blue else 0
            rgba.extend((red, green, blue, alpha))
    header = struct.pack(">IIBBBBB", size, size, 8, 6, 0, 0, 0)
    return b"\x89PNG\r\n\x1a\n" + _chunk(b"IHDR", header) + _chunk(b"IDAT", zlib.compress(bytes(rgba), 9)) + _chunk(b"IEND", b"")


class ShellIconProvider:
    """Caches native Windows Shell icons as Tk images."""

    def __init__(self, size: int = 16, text_gap: int | None = None) -> None:
        self.size = size
        self.text_gap = max(4, round(size * 0.3)) if text_gap is None else text_gap
        self.cache: dict[str, PhotoImage] = {}
        self.blank = PhotoImage(width=size + self.text_gap, height=size)

    def get(self, path: Path, is_dir: bool) -> PhotoImage:
        if os.name != "nt":
            return self.blank
        suffix = path.suffix.casefold()
        key = "<folder>" if is_dir else (str(path) if suffix in {".exe", ".lnk", ".ico"} else suffix or "<file>")
        if key not in self.cache:
            icon = self._load(path)
            self.cache[key] = self._with_text_gap(icon) if icon is not None else self.blank
        return self.cache[key]

    def _with_text_gap(self, icon: PhotoImage) -> PhotoImage:
        padded = PhotoImage(width=self.size + self.text_gap, height=self.size)
        padded.tk.call(str(padded), "copy", str(icon), "-to", 0, 0)
        return padded

    def _load(self, path: Path) -> PhotoImage | None:
        shell32, user32, gdi32 = ctypes.windll.shell32, ctypes.windll.user32, ctypes.windll.gdi32
        shell32.SHGetFileInfoW.restype = ctypes.c_size_t
        shell32.SHGetFileInfoW.argtypes = [ctypes.c_wchar_p, ctypes.c_uint32, ctypes.POINTER(_SHFILEINFO), ctypes.c_uint, ctypes.c_uint]
        user32.GetDC.restype = ctypes.c_void_p
        user32.GetDC.argtypes = [ctypes.c_void_p]
        user32.ReleaseDC.argtypes = [ctypes.c_void_p, ctypes.c_void_p]
        user32.DestroyIcon.argtypes = [ctypes.c_void_p]
        user32.DrawIconEx.argtypes = [ctypes.c_void_p, ctypes.c_int, ctypes.c_int, ctypes.c_void_p,
                                      ctypes.c_int, ctypes.c_int, ctypes.c_uint, ctypes.c_void_p, ctypes.c_uint]
        gdi32.CreateCompatibleDC.restype = ctypes.c_void_p
        gdi32.CreateCompatibleDC.argtypes = [ctypes.c_void_p]
        gdi32.CreateDIBSection.restype = ctypes.c_void_p
        gdi32.CreateDIBSection.argtypes = [ctypes.c_void_p, ctypes.POINTER(_BITMAPINFO), ctypes.c_uint,
                                           ctypes.POINTER(ctypes.c_void_p), ctypes.c_void_p, ctypes.c_uint]
        gdi32.SelectObject.restype = ctypes.c_void_p
        gdi32.SelectObject.argtypes = [ctypes.c_void_p, ctypes.c_void_p]
        gdi32.DeleteObject.argtypes = [ctypes.c_void_p]
        gdi32.DeleteDC.argtypes = [ctypes.c_void_p]
        info = _SHFILEINFO()
        # The small Shell handle reliably contains alpha on all supported Windows
        # versions. DrawIconEx scales it to the selected UI profile; some large
        # handles render fully transparent when converted through a 32-bit DIB.
        flags = 0x1 | 0x100
        if not shell32.SHGetFileInfoW(str(path), 0, ctypes.byref(info), ctypes.sizeof(info), flags):
            return None
        screen = user32.GetDC(None)
        memory = gdi32.CreateCompatibleDC(screen)
        bitmap_info = _BITMAPINFO()
        bitmap_info.bmiHeader.biSize = ctypes.sizeof(_BITMAPINFOHEADER)
        bitmap_info.bmiHeader.biWidth = self.size
        bitmap_info.bmiHeader.biHeight = -self.size
        bitmap_info.bmiHeader.biPlanes = 1
        bitmap_info.bmiHeader.biBitCount = 32
        bitmap_info.bmiHeader.biCompression = 0
        bits = ctypes.c_void_p()
        bitmap = gdi32.CreateDIBSection(memory, ctypes.byref(bitmap_info), 0, ctypes.byref(bits), None, 0)
        old = gdi32.SelectObject(memory, bitmap)
        ctypes.memset(bits.value, 0, self.size * self.size * 4)
        user32.DrawIconEx(memory, 0, 0, info.hIcon, self.size, self.size, 0, None, 0x3)
        raw = ctypes.string_at(bits.value, self.size * self.size * 4)
        gdi32.SelectObject(memory, old)
        gdi32.DeleteObject(bitmap)
        gdi32.DeleteDC(memory)
        user32.ReleaseDC(None, screen)
        user32.DestroyIcon(info.hIcon)
        try:
            encoded = base64.b64encode(_png_from_bgra(raw, self.size)).decode("ascii")
            return PhotoImage(data=encoded, format="png")
        except Exception:
            return None


import csv
import difflib
import hashlib
import os
from pathlib import Path
import tkinter as tk
from tkinter import messagebox, ttk


TEXT_SUFFIXES = {".txt", ".md", ".py", ".json", ".xml", ".html", ".htm", ".css", ".js",
                 ".ini", ".cfg", ".log", ".yaml", ".yml", ".sql", ".bat", ".ps1", ".c", ".h",
                 ".cpp", ".hpp", ".java", ".csv", ".tsv"}
TABLE_SUFFIXES = {".csv", ".tsv"}


def detect_compare_type(left: Path, right: Path) -> str:
    if left.is_dir() and right.is_dir():
        return "Folder"
    if left.suffix.casefold() in TABLE_SUFFIXES and right.suffix.casefold() in TABLE_SUFFIXES:
        return "Table"
    if left.suffix.casefold() in TEXT_SUFFIXES or right.suffix.casefold() in TEXT_SUFFIXES:
        return "Text"
    try:
        for path in (left, right):
            sample = path.read_bytes()[:4096]
            if b"\0" in sample:
                return "Binary"
            sample.decode("utf-8")
        return "Text"
    except (OSError, UnicodeDecodeError):
        return "Binary"


def file_hash(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def aligned_text(left: str, right: str) -> tuple[list[tuple[int | None, str, int | None, str]], list[int]]:
    a, b = left.splitlines(), right.splitlines()
    rows: list[tuple[int | None, str, int | None, str]] = []
    differences: list[int] = []
    matcher = difflib.SequenceMatcher(None, a, b, autojunk=False)
    for tag, a0, a1, b0, b1 in matcher.get_opcodes():
        length = max(a1 - a0, b1 - b0)
        for offset in range(length):
            has_left, has_right = a0 + offset < a1, b0 + offset < b1
            rows.append((a0 + offset + 1 if has_left else None, a[a0 + offset] if has_left else "",
                         b0 + offset + 1 if has_right else None, b[b0 + offset] if has_right else ""))
            if tag != "equal":
                differences.append(len(rows))
    return rows, differences


class SideBySideText(ttk.Frame):
    def __init__(self, master, left_lines, right_lines, differences, status_text=""):
        super().__init__(master)
        self.differences = differences
        self.diff_index = -1
        toolbar = ttk.Frame(self); toolbar.pack(fill="x")
        ttk.Button(toolbar, text="F7 Previous", command=self.previous).pack(side="left")
        ttk.Button(toolbar, text="F8 Next", command=self.next).pack(side="left", padx=3)
        ttk.Label(toolbar, text=status_text).pack(side="left", padx=10)
        body = ttk.Panedwindow(self, orient="horizontal"); body.pack(fill="both", expand=True)
        self.left = tk.Text(body, wrap="none", undo=False)
        self.right = tk.Text(body, wrap="none", undo=False)
        body.add(self.left, weight=1); body.add(self.right, weight=1)
        scroll = ttk.Scrollbar(self, orient="vertical", command=self._scroll)
        scroll.pack(side="right", fill="y")
        self.left.configure(yscrollcommand=scroll.set); self.right.configure(yscrollcommand=scroll.set)
        for widget, lines in ((self.left, left_lines), (self.right, right_lines)):
            widget.tag_configure("diff", background="#ffe1a8")
            widget.tag_configure("current", background="#ffb347")
            for display_row, item in enumerate(lines, 1):
                source_number, line = item if isinstance(item, tuple) else (display_row, item)
                number_text = "" if source_number is None else str(source_number)
                widget.insert("end", f"{number_text:>6}  {line}\n", "diff" if display_row in differences else "")
            widget.configure(state="disabled")

    def _scroll(self, *args):
        self.left.yview(*args); self.right.yview(*args)

    def next(self):
        if self.differences:
            self.diff_index = (self.diff_index + 1) % len(self.differences); self._show()

    def previous(self):
        if self.differences:
            self.diff_index = (self.diff_index - 1) % len(self.differences); self._show()

    def _show(self):
        line = self.differences[self.diff_index]
        for widget in (self.left, self.right):
            widget.see(f"{line}.0")
            widget.tag_remove("current", "1.0", "end")
            widget.tag_add("current", f"{line}.0", f"{line}.end")


class TextCompare(ttk.Frame):
    def __init__(self, master, left: Path, right: Path):
        super().__init__(master)
        a = left.read_text(encoding="utf-8", errors="replace")
        b = right.read_text(encoding="utf-8", errors="replace")
        rows, differences = aligned_text(a, b)
        view = SideBySideText(self, [(row[0], row[1]) for row in rows], [(row[2], row[3]) for row in rows], differences,
                              f"{len(differences)} different line(s)")
        view.pack(fill="both", expand=True)


class BinaryCompare(ttk.Frame):
    LIMIT = 256 * 1024

    def __init__(self, master, left: Path, right: Path):
        super().__init__(master)
        a, b = left.read_bytes()[:self.LIMIT], right.read_bytes()[:self.LIMIT]
        length = max(len(a), len(b)); different_offsets = []
        left_lines, right_lines, diff_lines = [], [], []
        for offset in range(0, length, 16):
            ca, cb = a[offset:offset + 16], b[offset:offset + 16]
            if ca != cb:
                different_offsets.extend(offset + index for index in range(max(len(ca), len(cb)))
                                         if (ca[index:index + 1] != cb[index:index + 1]))
                diff_lines.append(len(left_lines) + 1)
            def render(chunk):
                hexdump = " ".join(f"{byte:02X}" for byte in chunk)
                text = "".join(chr(byte) if 32 <= byte < 127 else "." for byte in chunk)
                return f"{offset:08X}  {hexdump:<47}  {text}"
            left_lines.append(render(ca)); right_lines.append(render(cb))
        status = f"SHA-256: {'identical' if file_hash(left) == file_hash(right) else 'different'}; first offset: "
        status += f"0x{different_offsets[0]:X}" if different_offsets else "none"
        SideBySideText(self, left_lines, right_lines, diff_lines, status).pack(fill="both", expand=True)


def folder_rows(left: Path, right: Path):
    left_items = {str(p.relative_to(left)).casefold(): p for p in left.rglob("*")}
    right_items = {str(p.relative_to(right)).casefold(): p for p in right.rglob("*")}
    for key in sorted(left_items.keys() | right_items.keys()):
        a, b = left_items.get(key), right_items.get(key)
        display = str((a.relative_to(left) if a else b.relative_to(right)))
        if a is None: status = "Right only"
        elif b is None: status = "Left only"
        elif a.is_dir() != b.is_dir(): status = "Type mismatch"
        elif a.is_dir(): status = "Identical"
        elif a.stat().st_size == b.stat().st_size and file_hash(a) == file_hash(b): status = "Identical"
        else: status = "Different"
        yield status, display, a, b


class FolderCompare(ttk.Frame):
    def __init__(self, master, left: Path, right: Path, open_detail):
        super().__init__(master)
        bar = ttk.Frame(self); bar.pack(fill="x")
        self.show_identical = tk.BooleanVar(value=False)
        ttk.Checkbutton(bar, text="Show identical", variable=self.show_identical, command=self.populate).pack(side="left")
        self.tree = ttk.Treeview(self, columns=("status", "path", "left", "right"), show="headings")
        for col, width in (("status", 110), ("path", 420), ("left", 130), ("right", 130)):
            self.tree.heading(col, text=col.title()); self.tree.column(col, width=width)
        self.tree.pack(fill="both", expand=True)
        self.rows = list(folder_rows(left, right)); self.open_detail = open_detail
        self.tree.bind("<Double-1>", self._open); self.populate()

    def populate(self):
        self.tree.delete(*self.tree.get_children())
        for status, path, left, right in self.rows:
            if status == "Identical" and not self.show_identical.get(): continue
            self.tree.insert("", "end", values=(status, path,
                "—" if left is None else ("<DIR>" if left.is_dir() else left.stat().st_size),
                "—" if right is None else ("<DIR>" if right.is_dir() else right.stat().st_size)),
                tags=(str(left or ""), str(right or "")))

    def _open(self, _event=None):
        selected = self.tree.selection()
        if selected:
            left, right = self.tree.item(selected[0], "tags")
            if left and right and Path(left).is_file() and Path(right).is_file(): self.open_detail(Path(left), Path(right))


class TableCompare(TextCompare):
    def __init__(self, master, left: Path, right: Path):
        def rows(path):
            delimiter = "\t" if path.suffix.casefold() == ".tsv" else ","
            with path.open("r", encoding="utf-8-sig", errors="replace", newline="") as stream:
                return [" | ".join(row) for row in csv.reader(stream, delimiter=delimiter)]
        ttk.Frame.__init__(self, master)
        a, b = "\n".join(rows(left)), "\n".join(rows(right))
        aligned, differences = aligned_text(a, b)
        SideBySideText(self, [(r[0], r[1]) for r in aligned], [(r[2], r[3]) for r in aligned], differences,
                       f"{len(differences)} different row(s)").pack(fill="both", expand=True)


class CompareWindow(tk.Toplevel):
    def __init__(self, master, config, save_config):
        super().__init__(master)
        self.config_data, self.save_config = config, save_config
        self.title("PFC Compare")
        self.geometry(config.get("compare", "geometry", fallback="1400x850"))
        self.protocol("WM_DELETE_WINDOW", self.close)
        self.notebook = ttk.Notebook(self, style="PFC.TNotebook"); self.notebook.pack(fill="both", expand=True)
        self.bind("<F7>", lambda _e: self._navigate("previous"))
        self.bind("<F8>", lambda _e: self._navigate("next"))
        self.bind("<Escape>", lambda _e: self.close_active())

    def add(self, left: Path, right: Path, requested="Auto"):
        kind = detect_compare_type(left, right) if requested == "Auto" else requested
        if left.is_dir() != right.is_dir():
            messagebox.showerror("Compare", "Select two files or two folders.", parent=self); return
        if kind == "Folder": frame = FolderCompare(self.notebook, left, right, self.add)
        elif kind == "Text": frame = TextCompare(self.notebook, left, right)
        elif kind == "Table": frame = TableCompare(self.notebook, left, right)
        else: frame = BinaryCompare(self.notebook, left, right)
        self.notebook.add(frame, text=f"{kind}: {left.name} ↔ {right.name}")
        self.notebook.select(frame); self.deiconify(); self.lift(); self.focus_force()

    def _navigate(self, method):
        frame = self.nametowidget(self.notebook.select())
        for child in frame.winfo_children():
            if isinstance(child, SideBySideText): getattr(child, method)(); return

    def close(self):
        if not self.config_data.has_section("compare"): self.config_data.add_section("compare")
        self.config_data.set("compare", "geometry", self.geometry())
        self.save_config(); self.destroy()

    def close_active(self):
        tabs = self.notebook.tabs()
        if len(tabs) <= 1:
            self.close()
            return
        current = self.notebook.select()
        widget = self.nametowidget(current)
        self.notebook.forget(current)
        widget.destroy()


import os
import configparser
import json
import subprocess
import sys
import tkinter as tk
import tkinter.font as tkfont
from datetime import datetime
from pathlib import Path
from tkinter import messagebox, simpledialog, ttk



class FilePane(ttk.Frame):
    columns = ("ext", "size", "modified", "attr")
    all_sort_columns = ("name", "ext", "size", "modified", "attr")
    base_widths = {"name": 300, "ext": 55, "size": 85, "modified": 135, "attr": 55}

    def __init__(self, master: tk.Misc, on_activate, on_change=lambda: None) -> None:
        super().__init__(master)
        self.on_activate = on_activate
        self.on_change = on_change
        self.path = Path.home()
        self.history: list[Path] = []
        self.sort_column = "name"
        self.reverse = False
        self.show_hidden = False
        self.show_system = False
        self.mode = "files"
        self.display_title = self.path.name or str(self.path)
        self._signature = None
        self.heading_labels = {"name": "Name", "ext": "Ext", "size": "Size", "modified": "Date Modified", "attr": "Attr"}
        self.icons = ShellIconProvider()

        bar = ttk.Frame(self)
        bar.pack(fill="x", pady=(0, 3))
        self.drive = ttk.Combobox(bar, state="readonly", width=8, values=[str(p) for p in roots()])
        self.drive.pack(side="left")
        self.drive.bind("<<ComboboxSelected>>", lambda _e: self.navigate(Path(self.drive.get())))
        ttk.Button(bar, text="↑", width=3, command=self.up).pack(side="left", padx=2)
        ttk.Button(bar, text="⌂", width=3, command=lambda: self.navigate(Path.home())).pack(side="left")
        self.path_var = tk.StringVar()
        entry = ttk.Entry(bar, textvariable=self.path_var)
        entry.pack(side="left", fill="x", expand=True, padx=(4, 0))
        entry.bind("<Return>", lambda _e: self.navigate(Path(self.path_var.get())))

        frame = ttk.Frame(self)
        frame.pack(fill="both", expand=True)
        self.tree = ttk.Treeview(frame, columns=self.columns, show="tree headings", selectmode="extended", style="Inactive.Treeview")
        self.tree.heading("#0", text="Name ▲", command=lambda: self.change_sort("name"))
        self.tree.column("#0", width=self.base_widths["name"], minwidth=120, stretch=True)
        for col in self.columns:
            marker = ""
            self.tree.heading(col, text=self.heading_labels[col] + marker, command=lambda c=col: self.change_sort(c))
            self.tree.column(col, width=self.base_widths[col], stretch=False, anchor="e" if col == "size" else "w")
        scroll = ttk.Scrollbar(frame, orient="vertical", command=self.tree.yview)
        horizontal = ttk.Scrollbar(frame, orient="horizontal", command=self.tree.xview)
        self.tree.configure(yscrollcommand=scroll.set, xscrollcommand=horizontal.set)
        horizontal.pack(side="bottom", fill="x")
        self.tree.pack(side="left", fill="both", expand=True)
        scroll.pack(side="right", fill="y")
        self.tree.bind("<Double-1>", self.open_selected)
        self.tree.bind("<Return>", self.open_selected)
        self.tree.bind("<FocusIn>", lambda _e: self.on_activate(self))
        self.status = ttk.Label(self, anchor="w")
        self.status.pack(fill="x", pady=(3, 0))
        self.navigate(self.path)

    def navigate(self, path: Path) -> None:
        try:
            path = path.expanduser().resolve()
            if not path.is_dir():
                raise NotADirectoryError(path)
            if path != self.path:
                self.history.append(self.path)
            self.path = path
            self.mode = "files"
            self.display_title = path.name or str(path)
            self.path_var.set(str(path))
            if os.name == "nt":
                self.drive.set(path.anchor)
            self.refresh()
            self.on_change()
        except OSError as exc:
            messagebox.showerror("Cannot open folder", str(exc))

    def up(self) -> None:
        self.navigate(self.path.parent)

    def change_sort(self, column: str) -> None:
        self.reverse = not self.reverse if self.sort_column == column else False
        self.sort_column = column
        for col in self.all_sort_columns:
            marker = (" ▲" if not self.reverse else " ▼") if col == self.sort_column else ""
            target = "#0" if col == "name" else col
            self.tree.heading(target, text=self.heading_labels[col] + marker)
        self.refresh()
        self.on_change()

    def refresh(self) -> None:
        selected = {self.tree.item(i, "tags")[0] for i in self.tree.selection() if self.tree.item(i, "tags")}
        scroll_position = self.tree.yview()[0] if self.tree.get_children() else 0.0
        self.tree.delete(*self.tree.get_children())
        try:
            entries = [p for p in self.path.iterdir()
                       if (self.show_hidden or not p.name.startswith(".")) and (self.show_system or not is_system(p))]
            self._signature = self.signature_for(entries)
            def key(p: Path):
                try:
                    stat = p.stat()
                    values = {"name": p.name.lower(), "ext": p.suffix.lower(), "size": stat.st_size,
                              "modified": stat.st_mtime, "attr": p.name.startswith(".")}
                    return (not p.is_dir(), values[self.sort_column])
                except OSError:
                    return (True, p.name.lower())
            entries.sort(key=key, reverse=self.reverse)
            total = 0
            for p in entries:
                try:
                    stat = p.stat()
                    is_dir = p.is_dir()
                    total += 0 if is_dir else stat.st_size
                    name = f"[{p.name}]" if is_dir else p.name
                    values = ("" if is_dir else p.suffix[1:], "<DIR>" if is_dir else format_size(stat.st_size),
                              datetime.fromtimestamp(stat.st_mtime).strftime("%Y-%m-%d %H:%M"),
                              ("d" if is_dir else "-") + ("h" if p.name.startswith(".") else "-"))
                    iid = self.tree.insert("", "end", text=name, image=self.icons.get(p, is_dir), values=values, tags=(str(p),))
                    if str(p) in selected:
                        self.tree.selection_add(iid)
                except OSError:
                    continue
            self.status.configure(text=f"{len(entries)} items   {format_size(total)}")
            current = self.tree.selection()
            children = self.tree.get_children()
            if not current and children:
                self.tree.selection_set(children[0])
                self.tree.focus(children[0])
                self.tree.see(children[0])
            elif children:
                self.tree.yview_moveto(scroll_position)
        except OSError as exc:
            messagebox.showerror("Cannot read folder", str(exc))

    @staticmethod
    def signature_for(entries) -> tuple:
        signature = []
        for path in entries:
            try:
                stat = path.stat()
                signature.append((path.name, stat.st_size, stat.st_mtime_ns, stat.st_mode))
            except OSError:
                signature.append((path.name, None, None, None))
        return tuple(sorted(signature))

    def refresh_if_changed(self) -> bool:
        if self.mode != "files":
            return False
        try:
            entries = [p for p in self.path.iterdir()
                       if (self.show_hidden or not p.name.startswith(".")) and (self.show_system or not is_system(p))]
            signature = self.signature_for(entries)
        except OSError:
            return False
        if signature == self._signature:
            return False
        self.refresh()
        return True

    def selected_paths(self) -> list[Path]:
        result = []
        for iid in self.tree.selection():
            tags = self.tree.item(iid, "tags")
            if tags:
                result.append(Path(tags[0]))
        return result

    def open_selected(self, _event=None) -> None:
        items = self.selected_paths()
        if not items:
            return
        item = items[0]
        if item.is_dir():
            self.navigate(item)
        else:
            try:
                os.startfile(item) if os.name == "nt" else subprocess.Popen(["xdg-open", str(item)])
            except OSError as exc:
                messagebox.showerror("Cannot open file", str(exc))

    def show_preview(self, item: Path) -> None:
        self.mode = "preview"
        self.display_title = item.name
        self.tree.delete(*self.tree.get_children())
        self.path_var.set(f"[Preview] {item}")
        try:
            stat = item.stat()
            details = [
                f"Name: {item.name}",
                f"Path: {item}",
                f"Size: {format_size(stat.st_size)}",
                f"Modified: {datetime.fromtimestamp(stat.st_mtime):%Y-%m-%d %H:%M:%S}",
                "",
            ]
            if item.is_dir():
                details.append("Folder preview: press Right to enter it.")
            elif item.suffix.lower() in {".txt", ".md", ".csv", ".json", ".xml", ".log", ".py", ".ini", ".yaml", ".yml"}:
                with item.open("r", encoding="utf-8", errors="replace") as stream:
                    details.extend(line.rstrip("\r\n") for _, line in zip(range(300), stream))
            else:
                details.append("Binary file: metadata preview only.")
            for line in details:
                self.tree.insert("", "end", text=line, values=("", "", "", ""))
            self.status.configure(text=f"Previewing {item.name}")
            self.on_change()
        except OSError as exc:
            messagebox.showerror("Preview failed", str(exc))

    def search(self, query: str) -> None:
        self.mode = "search"
        self.display_title = f"Search: {query}"
        self.tree.delete(*self.tree.get_children())
        self.path_var.set(f"[Search] {query} in {self.path}")
        query = query.casefold()
        count = 0
        try:
            for item in self.path.rglob("*"):
                if query not in item.name.casefold():
                    continue
                try:
                    stat = item.stat()
                    is_dir = item.is_dir()
                    self.tree.insert("", "end", text=str(item.relative_to(self.path)), image=self.icons.get(item, is_dir), values=(
                        "" if is_dir else item.suffix[1:], "<DIR>" if is_dir else format_size(stat.st_size),
                        datetime.fromtimestamp(stat.st_mtime).strftime("%Y-%m-%d %H:%M"), "d-" if is_dir else "--"),
                        tags=(str(item),))
                    count += 1
                    if count >= 2000:
                        break
                except OSError:
                    continue
            self.status.configure(text=f"{count} match(es)" + (" (limited to 2000)" if count == 2000 else ""))
            self.on_change()
        except OSError as exc:
            messagebox.showerror("Search failed", str(exc))

    def toggle_hidden(self) -> None:
        self.show_hidden = not self.show_hidden
        self.refresh()
        self.on_change()

    def toggle_system(self) -> None:
        self.show_system = not self.show_system
        self.refresh()
        self.on_change()

    def set_active_appearance(self, active: bool) -> None:
        self.tree.configure(style="Active.Treeview" if active else "Inactive.Treeview")

    def apply_scale(self, scale: float) -> None:
        icon_size = max(16, round(16 * scale))
        if self.icons.size != icon_size:
            self.icons = ShellIconProvider(icon_size)
        self.tree.column("#0", width=round(self.base_widths["name"] * scale), minwidth=120, stretch=True)
        for column in self.columns:
            self.tree.column(column, width=round(self.base_widths[column] * scale))
        self.refresh()


class PaneTabs(ttk.Notebook):
    def __init__(self, master: tk.Misc, on_activate, on_change=lambda: None, initial_paths=None) -> None:
        super().__init__(master, style="PFC.TNotebook")
        self.on_activate = on_activate
        self.on_change = on_change
        self.bind("<<NotebookTabChanged>>", lambda _e: self._tab_changed())
        for path in initial_paths or [Path.home()]:
            self.add_tab(path, notify=False)

    def add_tab(self, path: Path, notify: bool = True) -> FilePane:
        pane = FilePane(self, self.on_activate, self._pane_changed)
        pane.navigate(path)
        self.add(pane, text=path.name or str(path))
        self.select(pane)
        pane.tree.focus_set()
        if notify:
            self.on_change()
        return pane

    def _pane_changed(self) -> None:
        if not self.tabs():
            self.on_change()
            return
        try:
            pane = self.current()
            self.tab(pane, text=pane.display_title)
        except (tk.TclError, AttributeError):
            pass
        self.on_change()

    def _tab_changed(self) -> None:
        try:
            self.on_activate(self.current())
        except tk.TclError:
            return
        self.on_change()

    def current(self) -> FilePane:
        return self.nametowidget(self.select())

    def close_current(self) -> None:
        if len(self.tabs()) > 1:
            self.forget(self.select())
            self.on_change()

    def panes(self) -> list[FilePane]:
        return [self.nametowidget(tab) for tab in self.tabs()]


class Commander(tk.Tk):
    def __init__(self) -> None:
        super().__init__()
        self._ready = False
        self.ini_path = self._find_ini_path()
        self.config_data = configparser.ConfigParser()
        self.config_data.read(self.ini_path, encoding="utf-8")
        self.title("Python File Commander")
        self.geometry(self.config_data.get("window", "geometry", fallback="1200x720"))
        self.minsize(800, 480)
        self.active: FilePane | None = None
        self.compare_window = None
        self.font_size_var = tk.StringVar(value=self.config_data.get("view", "font_size", fallback="small"))
        self._font_scales = {"small": 1.0, "medium": 1.5, "large": 2.0, "huge": 3.0}
        self._base_font_sizes = {}
        for name in ("TkDefaultFont", "TkTextFont", "TkMenuFont", "TkHeadingFont", "TkCaptionFont"):
            try:
                self._base_font_sizes[name] = tkfont.nametofont(name).cget("size")
            except tk.TclError:
                pass
        style = ttk.Style(self)
        style.configure("Active.Treeview", background="white", fieldbackground="white", indent=6)
        style.map("Active.Treeview", background=[("selected", "#1683e2")], foreground=[("selected", "white")])
        style.configure("Inactive.Treeview", background="white", fieldbackground="white", indent=6)
        style.map("Inactive.Treeview", background=[("selected", "#91a9bd")], foreground=[("selected", "white")])
        style.configure("PFC.TNotebook", background="#9eafbd", borderwidth=1)
        style.configure("PFC.TNotebook.Tab", background="#c7d3dd", foreground="#243442",
                        padding=(10, 5), borderwidth=1)
        style.map("PFC.TNotebook.Tab",
                  background=[("selected", "#1683e2"), ("active", "#dce7ef")],
                  foreground=[("selected", "#005a9e"), ("active", "#10202c")],
                  expand=[("selected", (1, 1, 1, 0))])
        flat_item_layout = [("Treeitem.padding", {"sticky": "nswe", "children": [
            ("Treeitem.image", {"side": "left", "sticky": ""}),
            ("Treeitem.text", {"side": "left", "sticky": ""}),
        ]})]
        style.layout("Active.Treeview.Item", flat_item_layout)
        style.layout("Inactive.Treeview.Item", flat_item_layout)
        self.apply_font_size(save=False)
        self._build_menu()
        split = ttk.Panedwindow(self, orient="horizontal")
        split.pack(fill="both", expand=True, padx=5, pady=5)
        left_paths = self._saved_paths("left")
        right_paths = self._saved_paths("right")
        self.left_tabs = PaneTabs(split, self.set_active, self.save_config, left_paths)
        self.right_tabs = PaneTabs(split, self.set_active, self.save_config, right_paths)
        self.left = self.left_tabs.current()
        self.right = self.right_tabs.current()
        split.add(self.left_tabs, weight=1)
        split.add(self.right_tabs, weight=1)
        self._restore_tab(self.left_tabs, "left")
        self._restore_tab(self.right_tabs, "right")
        self._restore_panel_options(self.left_tabs, "left")
        self._restore_panel_options(self.right_tabs, "right")
        self.active = self.right_tabs.current() if self.config_data.get("state", "active_panel", fallback="left") == "right" else self.left_tabs.current()
        self.apply_font_size(save=False)
        actions = ttk.Frame(self)
        actions.pack(fill="x", padx=5, pady=(0, 5))
        for text, command in (("F3 Preview", self.preview), ("F4 Search", self.search), ("F5 Copy", self.copy), ("F6 Move", self.move),
                              ("F7 New folder", self.mkdir), ("Del Delete", self.delete), ("F2 Rename", self.rename),
                              ("F9 Compare", self.compare_selected)):
            ttk.Button(actions, text=text, command=command).pack(side="left", fill="x", expand=True, padx=1)
        defaults = {
            "rename": "<F2>", "preview": "<F3>", "search": "<F4>", "copy": "<F5>",
            "move": "<F6>", "new_folder": "<F7>", "delete": "<Delete>", "refresh": "<Control-r>",
            "enter_folder": "<Right>", "parent_folder": "<Left>", "new_tab": "<Control-Up>",
            "close_tab": "<Control-w>", "select_all": "<Control-a>",
            "copy_path": "<Control-Shift-C>", "toggle_hidden": "<Control-h>",
            "compare": "<F9>",
        }
        commands = {
            "rename": self.rename, "preview": self.preview, "search": self.search, "copy": self.copy,
            "move": self.move, "new_folder": self.mkdir, "delete": self.delete, "refresh": self.refresh,
            "enter_folder": self.enter_folder, "parent_folder": self.parent_folder, "new_tab": self.new_tab,
            "close_tab": self.close_tab, "select_all": self.select_all,
            "copy_path": self.copy_path, "toggle_hidden": self.toggle_hidden,
            "compare": self.compare_selected,
        }
        if not self.config_data.has_section("hotkeys"):
            self.config_data.add_section("hotkeys")
        for name, default in defaults.items():
            key = self.config_data.get("hotkeys", name, fallback=default)
            self.config_data.set("hotkeys", name, key)
            self.bind_all(key, lambda _e, fn=commands[name]: fn())
        self.protocol("WM_DELETE_WINDOW", self.close_app)
        self._ready = True
        self._save_job = None
        self._auto_refresh_job = None
        self.bind("<Configure>", self._schedule_save)
        self.set_active(self.active)
        self.save_config()
        self._schedule_auto_refresh(250)

    @staticmethod
    def _find_ini_path() -> Path:
        executable = Path(sys.argv[0]).resolve()
        if executable.name.casefold() == "pfc.py":
            return executable.with_name("pfc.ini")
        return Path(__file__).resolve().parents[1] / "pfc.ini"

    def _saved_paths(self, side: str) -> list[Path]:
        try:
            paths = json.loads(self.config_data.get(side, "tabs", fallback="[]"))
        except (json.JSONDecodeError, TypeError):
            paths = []
        candidates = [Path(value).expanduser() for value in paths]
        valid = [path for path in candidates if path.is_dir()]
        return valid or [Path.home()]

    def _restore_tab(self, tabs: PaneTabs, side: str) -> None:
        index = self.config_data.getint(side, "selected", fallback=0)
        if tabs.tabs():
            tabs.select(tabs.tabs()[min(max(index, 0), len(tabs.tabs()) - 1)])

    def _restore_panel_options(self, tabs: PaneTabs, side: str) -> None:
        column = self.config_data.get(side, "sort_column", fallback="name")
        descending = self.config_data.getboolean(side, "sort_descending", fallback=False)
        show_hidden = self.config_data.getboolean(side, "show_hidden", fallback=False)
        show_system = self.config_data.getboolean(side, "show_system", fallback=False)
        for pane in tabs.panes():
            pane.sort_column = column if column in pane.all_sort_columns else "name"
            pane.reverse = descending
            pane.show_hidden = show_hidden
            pane.show_system = show_system
            for col in pane.all_sort_columns:
                marker = (" ▼" if descending else " ▲") if col == pane.sort_column else ""
                pane.tree.heading("#0" if col == "name" else col, text=pane.heading_labels[col] + marker)
            pane.refresh()

    def _schedule_save(self, _event=None) -> None:
        if not self._ready:
            return
        if self._save_job is not None:
            self.after_cancel(self._save_job)
        self._save_job = self.after(250, self.save_config)

    def save_config(self) -> None:
        if not self._ready:
            return
        for side, tabs in (("left", self.left_tabs), ("right", self.right_tabs)):
            if not self.config_data.has_section(side):
                self.config_data.add_section(side)
            panes = tabs.panes()
            self.config_data.set(side, "tabs", json.dumps([str(p.path) for p in panes]))
            self.config_data.set(side, "selected", str(tabs.index(tabs.select())))
            current = tabs.current()
            self.config_data.set(side, "sort_column", current.sort_column)
            self.config_data.set(side, "sort_descending", str(current.reverse).lower())
            self.config_data.set(side, "show_hidden", str(current.show_hidden).lower())
            self.config_data.set(side, "show_system", str(current.show_system).lower())
        if not self.config_data.has_section("window"):
            self.config_data.add_section("window")
        if not self.config_data.has_section("state"):
            self.config_data.add_section("state")
        if not self.config_data.has_section("view"):
            self.config_data.add_section("view")
        if not self.config_data.has_section("refresh"):
            self.config_data.add_section("refresh")
        self.config_data.set("window", "geometry", self.geometry())
        self.config_data.set("state", "active_panel", "left" if self.active in self.left_tabs.panes() else "right")
        self.config_data.set("view", "font_size", self.font_size_var.get())
        refresh_defaults = {"auto_refresh": "true", "active_interval_ms": "2000",
                            "background_interval_ms": "10000", "network_interval_ms": "5000"}
        for key, value in refresh_defaults.items():
            if not self.config_data.has_option("refresh", key):
                self.config_data.set("refresh", key, value)
        temporary = self.ini_path.with_suffix(".ini.tmp")
        try:
            with temporary.open("w", encoding="utf-8") as stream:
                self.config_data.write(stream)
            temporary.replace(self.ini_path)
        except OSError:
            pass

    def close_app(self) -> None:
        if self._auto_refresh_job is not None:
            self.after_cancel(self._auto_refresh_job)
        self.save_config()
        self.destroy()

    def _schedule_auto_refresh(self, delay=None) -> None:
        if not self.winfo_exists():
            return
        if delay is None:
            focused = self.focus_displayof() is not None
            paths = (self.left_tabs.current().path, self.right_tabs.current().path)
            network = any(str(path).startswith("\\\\") for path in paths)
            key = "network_interval_ms" if network else ("active_interval_ms" if focused else "background_interval_ms")
            delay = self.config_data.getint("refresh", key, fallback=5000)
        self._auto_refresh_job = self.after(max(500, delay), self._auto_refresh_tick)

    def _auto_refresh_tick(self) -> None:
        self._auto_refresh_job = None
        if self.config_data.getboolean("refresh", "auto_refresh", fallback=True):
            self.left_tabs.current().refresh_if_changed()
            self.right_tabs.current().refresh_if_changed()
        self._schedule_auto_refresh()

    def _build_menu(self) -> None:
        menu_font = tkfont.nametofont("TkMenuFont")
        header = ttk.Frame(self, padding=(5, 2))
        header.pack(fill="x")
        ttk.Label(header, text="Python File Commander", font=tkfont.nametofont("TkCaptionFont")).pack(side="left", padx=(2, 10))
        files = tk.Menu(self, tearoff=False, font=menu_font)
        files.add_command(label="Preview in other panel\tF3", command=self.preview)
        files.add_command(label="Search\tF4", command=self.search)
        files.add_command(label="Compare selected\tF9", command=self.compare_selected)
        files.add_command(label="Rename\tF2", command=self.rename)
        files.add_separator()
        files.add_command(label="Exit", command=self.destroy)
        files_button = tk.Menubutton(header, text="Files", menu=files, font=menu_font, relief="flat", padx=6)
        files_button.pack(side="left")
        view = tk.Menu(self, tearoff=False, font=menu_font)
        visibility = tk.Menu(view, tearoff=False, font=menu_font)
        self.show_hidden_var = tk.BooleanVar(value=False)
        self.show_system_var = tk.BooleanVar(value=False)
        visibility.add_checkbutton(label="Show Hidden", variable=self.show_hidden_var,
                                   command=self.set_hidden_visibility)
        visibility.add_checkbutton(label="Show System", variable=self.show_system_var,
                                   command=self.set_system_visibility)
        view.add_cascade(label="File Visibility", menu=visibility)
        font_size = tk.Menu(view, tearoff=False, font=menu_font)
        for label, value in (("Small (100%)", "small"), ("Medium (150%)", "medium"),
                             ("Large (200%)", "large"), ("Huge (300%)", "huge")):
            font_size.add_radiobutton(label=label, value=value, variable=self.font_size_var,
                                      command=self.apply_font_size)
        view.add_cascade(label="Font Size", menu=font_size)
        view_button = tk.Menubutton(header, text="View", menu=view, font=menu_font, relief="flat", padx=6)
        view_button.pack(side="left")
        self.config(menu="")

    def set_active(self, pane: FilePane) -> None:
        self.active = pane
        self.show_hidden_var.set(pane.show_hidden)
        self.show_system_var.set(pane.show_system)
        if hasattr(self, "left_tabs"):
            for candidate in self.left_tabs.panes() + self.right_tabs.panes():
                candidate.set_active_appearance(candidate is pane)
        self.save_config()

    def panes(self) -> tuple[FilePane, FilePane]:
        source = self.active or self.left_tabs.current()
        left_panes = [self.left_tabs.nametowidget(tab) for tab in self.left_tabs.tabs()]
        return (source, self.right_tabs.current() if source in left_panes else self.left_tabs.current())

    def refresh(self) -> None:
        self.left_tabs.current().refresh(); self.right_tabs.current().refresh()

    def open(self) -> None:
        self.panes()[0].open_selected()

    def enter_folder(self) -> None:
        self.open()

    def parent_folder(self) -> None:
        self.panes()[0].up()

    def preview(self) -> None:
        source, target = self.panes()
        items = source.selected_paths()
        if items:
            target.show_preview(items[0])

    def search(self) -> None:
        source, _ = self.panes()
        query = simpledialog.askstring("Search", "File or folder name contains:", parent=self)
        if query:
            source.search(query)

    def new_tab(self) -> None:
        source, _ = self.panes()
        tabs = self.left_tabs if source in [self.left_tabs.nametowidget(t) for t in self.left_tabs.tabs()] else self.right_tabs
        self.active = tabs.add_tab(source.path)

    def close_tab(self) -> None:
        source, _ = self.panes()
        tabs = self.left_tabs if source in [self.left_tabs.nametowidget(t) for t in self.left_tabs.tabs()] else self.right_tabs
        tabs.close_current()
        self.active = tabs.current()

    def select_all(self) -> None:
        source, _ = self.panes()
        source.tree.selection_set(source.tree.get_children())

    def copy_path(self) -> None:
        source, _ = self.panes()
        items = source.selected_paths()
        value = str(items[0] if items else source.path)
        self.clipboard_clear(); self.clipboard_append(value)

    def toggle_hidden(self) -> None:
        source = self.panes()[0]
        source.toggle_hidden()
        self.show_hidden_var.set(source.show_hidden)

    def set_hidden_visibility(self) -> None:
        source = self.panes()[0]
        source.show_hidden = self.show_hidden_var.get()
        source.refresh(); source.on_change()

    def set_system_visibility(self) -> None:
        source = self.panes()[0]
        source.show_system = self.show_system_var.get()
        source.refresh(); source.on_change()

    def compare_selected(self) -> None:
        source, target = self.panes()
        left_items = self.left_tabs.current().selected_paths()
        right_items = self.right_tabs.current().selected_paths()
        if len(left_items) == 1 and len(right_items) == 1:
            left, right = left_items[0], right_items[0]
        else:
            active_items = source.selected_paths()
            if len(active_items) != 2:
                messagebox.showinfo("Compare", "Select one item in each panel, or two items in the active panel.", parent=self)
                return
            left, right = active_items
        try:
            if self.compare_window is None or not self.compare_window.winfo_exists():
                self.compare_window = CompareWindow(self, self.config_data, self.save_config)
            self.compare_window.add(left, right)
        except OSError as exc:
            messagebox.showerror("Compare failed", str(exc), parent=self)

    def apply_font_size(self, save: bool = True) -> None:
        scale = self._font_scales.get(self.font_size_var.get(), 1.0)
        if self.font_size_var.get() not in self._font_scales:
            self.font_size_var.set("small")
        for name, base in self._base_font_sizes.items():
            size = max(1, round(abs(base) * scale))
            tkfont.nametofont(name).configure(size=-size if base < 0 else size)
        row_height = max(22, round(22 * scale))
        ttk.Style(self).configure("Active.Treeview", rowheight=row_height)
        ttk.Style(self).configure("Inactive.Treeview", rowheight=row_height)
        if hasattr(self, "left_tabs"):
            for pane in self.left_tabs.panes() + self.right_tabs.panes():
                pane.apply_scale(scale)
        if save:
            self.save_config()

    def _run(self, verb: str, operation) -> None:
        source, target = self.panes()
        items = source.selected_paths()
        if not items:
            return
        if not messagebox.askyesno(verb, f"{verb} {len(items)} selected item(s) to:\n{target.path}?"):
            return
        try:
            operation(items, target.path)
            self.refresh()
        except OSError as exc:
            messagebox.showerror(f"{verb} failed", str(exc))

    def copy(self) -> None:
        self._run("Copy", copy_items)

    def move(self) -> None:
        self._run("Move", move_items)

    def delete(self) -> None:
        source, _ = self.panes()
        items = source.selected_paths()
        if items and messagebox.askyesno("Permanent delete", f"Permanently delete {len(items)} selected item(s)?"):
            try:
                delete_items(items); self.refresh()
            except OSError as exc:
                messagebox.showerror("Delete failed", str(exc))

    def mkdir(self) -> None:
        source, _ = self.panes()
        name = simpledialog.askstring("New folder", "Folder name:", parent=self)
        if name:
            try:
                (source.path / name).mkdir(); source.refresh()
            except OSError as exc:
                messagebox.showerror("Create failed", str(exc))

    def rename(self) -> None:
        source, _ = self.panes()
        items = source.selected_paths()
        if len(items) != 1:
            messagebox.showinfo("Rename", "Select exactly one item."); return
        name = simpledialog.askstring("Rename", "New name:", initialvalue=items[0].name, parent=self)
        if name and name != items[0].name:
            try:
                items[0].rename(items[0].with_name(name)); self.refresh()
            except OSError as exc:
                messagebox.showerror("Rename failed", str(exc))


def main() -> None:
    Commander().mainloop()


if __name__ == "__main__":
    main()
