"""Portable Python File Commander.

Generated from the pycommander package. Requires only Python 3.10+ with Tk.
Do not edit this file directly; run tools/build_single_file.py after source changes.
"""

from __future__ import annotations

import os
import shutil
import ctypes
from pathlib import Path


def copy_items(items: list[Path], destination: Path) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    for source in items:
        target = destination / source.name
        if source.is_dir():
            shutil.copytree(source, target, dirs_exist_ok=True)
        else:
            shutil.copy2(source, target)


def move_items(items: list[Path], destination: Path) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    for source in items:
        shutil.move(str(source), str(destination / source.name))


def delete_items(items: list[Path]) -> None:
    for item in items:
        if item.is_dir() and not item.is_symlink():
            shutil.rmtree(item)
        else:
            item.unlink()


def format_size(size: int) -> str:
    value = float(size)
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if value < 1024 or unit == "TB":
            return f"{value:.0f} {unit}" if unit == "B" else f"{value:.1f} {unit}"
        value /= 1024
    return str(size)


def roots() -> list[Path]:
    if os.name != "nt":
        return [Path("/")]
    return [Path(f"{letter}:\\") for letter in "ABCDEFGHIJKLMNOPQRSTUVWXYZ" if Path(f"{letter}:\\").exists()]


def is_system(path: Path) -> bool:
    """Return whether Windows marks a path with the SYSTEM attribute."""
    if os.name != "nt":
        return False
    attributes = ctypes.windll.kernel32.GetFileAttributesW(str(path))
    return attributes != 0xFFFFFFFF and bool(attributes & 0x4)


import os
import configparser
import json
import subprocess
import sys
import tkinter as tk
from datetime import datetime
from pathlib import Path
from tkinter import messagebox, simpledialog, ttk



class FilePane(ttk.Frame):
    columns = ("name", "ext", "size", "modified", "attr")

    def __init__(self, master: tk.Misc, on_activate, on_change=lambda: None) -> None:
        super().__init__(master)
        self.on_activate = on_activate
        self.on_change = on_change
        self.path = Path.home()
        self.history: list[Path] = []
        self.sort_column = "name"
        self.reverse = False
        self.show_hidden = True
        self.show_system = True
        self.mode = "files"
        self.display_title = self.path.name or str(self.path)
        self.heading_labels = {"name": "Name", "ext": "Ext", "size": "Size", "modified": "Date", "attr": "Attr"}

        bar = ttk.Frame(self)
        bar.pack(fill="x", pady=(0, 3))
        self.drive = ttk.Combobox(bar, state="readonly", width=8, values=[str(p) for p in roots()])
        self.drive.pack(side="left")
        self.drive.bind("<<ComboboxSelected>>", lambda _e: self.navigate(Path(self.drive.get())))
        ttk.Button(bar, text="↑", width=3, command=self.up).pack(side="left", padx=2)
        ttk.Button(bar, text="⌂", width=3, command=lambda: self.navigate(Path.home())).pack(side="left")
        self.path_var = tk.StringVar()
        entry = ttk.Entry(bar, textvariable=self.path_var)
        entry.pack(side="left", fill="x", expand=True, padx=(4, 0))
        entry.bind("<Return>", lambda _e: self.navigate(Path(self.path_var.get())))

        frame = ttk.Frame(self)
        frame.pack(fill="both", expand=True)
        self.tree = ttk.Treeview(frame, columns=self.columns, show="headings", selectmode="extended", style="Inactive.Treeview")
        widths = {"name": 260, "ext": 55, "size": 85, "modified": 135, "attr": 55}
        for col in self.columns:
            marker = " ▲" if col == self.sort_column else ""
            self.tree.heading(col, text=self.heading_labels[col] + marker, command=lambda c=col: self.change_sort(c))
            self.tree.column(col, width=widths[col], stretch=col == "name", anchor="e" if col == "size" else "w")
        scroll = ttk.Scrollbar(frame, orient="vertical", command=self.tree.yview)
        self.tree.configure(yscrollcommand=scroll.set)
        self.tree.pack(side="left", fill="both", expand=True)
        scroll.pack(side="right", fill="y")
        self.tree.bind("<Double-1>", self.open_selected)
        self.tree.bind("<Return>", self.open_selected)
        self.tree.bind("<FocusIn>", lambda _e: self.on_activate(self))
        self.status = ttk.Label(self, anchor="w")
        self.status.pack(fill="x", pady=(3, 0))
        self.navigate(self.path)

    def navigate(self, path: Path) -> None:
        try:
            path = path.expanduser().resolve()
            if not path.is_dir():
                raise NotADirectoryError(path)
            if path != self.path:
                self.history.append(self.path)
            self.path = path
            self.mode = "files"
            self.display_title = path.name or str(path)
            self.path_var.set(str(path))
            if os.name == "nt":
                self.drive.set(path.anchor)
            self.refresh()
            self.on_change()
        except OSError as exc:
            messagebox.showerror("Cannot open folder", str(exc))

    def up(self) -> None:
        self.navigate(self.path.parent)

    def change_sort(self, column: str) -> None:
        self.reverse = not self.reverse if self.sort_column == column else False
        self.sort_column = column
        for col in self.columns:
            marker = (" ▲" if not self.reverse else " ▼") if col == self.sort_column else ""
            self.tree.heading(col, text=self.heading_labels[col] + marker)
        self.refresh()
        self.on_change()

    def refresh(self) -> None:
        selected = {self.tree.item(i, "tags")[0] for i in self.tree.selection() if self.tree.item(i, "tags")}
        self.tree.delete(*self.tree.get_children())
        try:
            entries = [p for p in self.path.iterdir()
                       if (self.show_hidden or not p.name.startswith(".")) and (self.show_system or not is_system(p))]
            def key(p: Path):
                try:
                    stat = p.stat()
                    values = {"name": p.name.lower(), "ext": p.suffix.lower(), "size": stat.st_size,
                              "modified": stat.st_mtime, "attr": p.name.startswith(".")}
                    return (not p.is_dir(), values[self.sort_column])
                except OSError:
                    return (True, p.name.lower())
            entries.sort(key=key, reverse=self.reverse)
            total = 0
            for p in entries:
                try:
                    stat = p.stat()
                    is_dir = p.is_dir()
                    total += 0 if is_dir else stat.st_size
                    icon = self.icon_for(p, is_dir)
                    values = (f"{icon} [{p.name}]" if is_dir else f"{icon} {p.name}", "" if is_dir else p.suffix[1:],
                              "<DIR>" if is_dir else format_size(stat.st_size),
                              datetime.fromtimestamp(stat.st_mtime).strftime("%Y-%m-%d %H:%M"),
                              ("d" if is_dir else "-") + ("h" if p.name.startswith(".") else "-"))
                    iid = self.tree.insert("", "end", values=values, tags=(str(p),))
                    if str(p) in selected:
                        self.tree.selection_add(iid)
                except OSError:
                    continue
            self.status.configure(text=f"{len(entries)} items   {format_size(total)}")
            current = self.tree.selection()
            children = self.tree.get_children()
            if not current and children:
                self.tree.selection_set(children[0])
                self.tree.focus(children[0])
                self.tree.see(children[0])
        except OSError as exc:
            messagebox.showerror("Cannot read folder", str(exc))

    def selected_paths(self) -> list[Path]:
        result = []
        for iid in self.tree.selection():
            tags = self.tree.item(iid, "tags")
            if tags:
                result.append(Path(tags[0]))
        return result

    @staticmethod
    def icon_for(path: Path, is_dir: bool | None = None) -> str:
        if is_dir if is_dir is not None else path.is_dir():
            return "📁"
        suffix = path.suffix.casefold()
        if suffix in {".png", ".jpg", ".jpeg", ".gif", ".bmp", ".webp", ".svg"}:
            return "🖼"
        if suffix in {".zip", ".7z", ".rar", ".tar", ".gz"}:
            return "📦"
        if suffix in {".pdf", ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx", ".txt", ".md"}:
            return "📄"
        return "▫"

    def open_selected(self, _event=None) -> None:
        items = self.selected_paths()
        if not items:
            return
        item = items[0]
        if item.is_dir():
            self.navigate(item)
        else:
            try:
                os.startfile(item) if os.name == "nt" else subprocess.Popen(["xdg-open", str(item)])
            except OSError as exc:
                messagebox.showerror("Cannot open file", str(exc))

    def show_preview(self, item: Path) -> None:
        self.mode = "preview"
        self.display_title = item.name
        self.tree.delete(*self.tree.get_children())
        self.path_var.set(f"[Preview] {item}")
        try:
            stat = item.stat()
            details = [
                f"Name: {item.name}",
                f"Path: {item}",
                f"Size: {format_size(stat.st_size)}",
                f"Modified: {datetime.fromtimestamp(stat.st_mtime):%Y-%m-%d %H:%M:%S}",
                "",
            ]
            if item.is_dir():
                details.append("Folder preview: press Right to enter it.")
            elif item.suffix.lower() in {".txt", ".md", ".csv", ".json", ".xml", ".log", ".py", ".ini", ".yaml", ".yml"}:
                with item.open("r", encoding="utf-8", errors="replace") as stream:
                    details.extend(line.rstrip("\r\n") for _, line in zip(range(300), stream))
            else:
                details.append("Binary file: metadata preview only.")
            for line in details:
                self.tree.insert("", "end", values=(line, "", "", "", ""))
            self.status.configure(text=f"Previewing {item.name}")
            self.on_change()
        except OSError as exc:
            messagebox.showerror("Preview failed", str(exc))

    def search(self, query: str) -> None:
        self.mode = "search"
        self.display_title = f"Search: {query}"
        self.tree.delete(*self.tree.get_children())
        self.path_var.set(f"[Search] {query} in {self.path}")
        query = query.casefold()
        count = 0
        try:
            for item in self.path.rglob("*"):
                if query not in item.name.casefold():
                    continue
                try:
                    stat = item.stat()
                    is_dir = item.is_dir()
                    icon = self.icon_for(item, is_dir)
                    self.tree.insert("", "end", values=(f"{icon} {item.relative_to(self.path)}",
                        "" if is_dir else item.suffix[1:], "<DIR>" if is_dir else format_size(stat.st_size),
                        datetime.fromtimestamp(stat.st_mtime).strftime("%Y-%m-%d %H:%M"), "d-" if is_dir else "--"),
                        tags=(str(item),))
                    count += 1
                    if count >= 2000:
                        break
                except OSError:
                    continue
            self.status.configure(text=f"{count} match(es)" + (" (limited to 2000)" if count == 2000 else ""))
            self.on_change()
        except OSError as exc:
            messagebox.showerror("Search failed", str(exc))

    def toggle_hidden(self) -> None:
        self.show_hidden = not self.show_hidden
        self.refresh()
        self.on_change()

    def toggle_system(self) -> None:
        self.show_system = not self.show_system
        self.refresh()
        self.on_change()

    def set_active_appearance(self, active: bool) -> None:
        self.tree.configure(style="Active.Treeview" if active else "Inactive.Treeview")


class PaneTabs(ttk.Notebook):
    def __init__(self, master: tk.Misc, on_activate, on_change=lambda: None, initial_paths=None) -> None:
        super().__init__(master)
        self.on_activate = on_activate
        self.on_change = on_change
        self.bind("<<NotebookTabChanged>>", lambda _e: self._tab_changed())
        for path in initial_paths or [Path.home()]:
            self.add_tab(path, notify=False)

    def add_tab(self, path: Path, notify: bool = True) -> FilePane:
        pane = FilePane(self, self.on_activate, self._pane_changed)
        pane.navigate(path)
        self.add(pane, text=path.name or str(path))
        self.select(pane)
        pane.tree.focus_set()
        if notify:
            self.on_change()
        return pane

    def _pane_changed(self) -> None:
        if not self.tabs():
            self.on_change()
            return
        try:
            pane = self.current()
            self.tab(pane, text=pane.display_title)
        except (tk.TclError, AttributeError):
            pass
        self.on_change()

    def _tab_changed(self) -> None:
        try:
            self.on_activate(self.current())
        except tk.TclError:
            return
        self.on_change()

    def current(self) -> FilePane:
        return self.nametowidget(self.select())

    def close_current(self) -> None:
        if len(self.tabs()) > 1:
            self.forget(self.select())
            self.on_change()

    def panes(self) -> list[FilePane]:
        return [self.nametowidget(tab) for tab in self.tabs()]


class Commander(tk.Tk):
    def __init__(self) -> None:
        super().__init__()
        self._ready = False
        self.ini_path = self._find_ini_path()
        self.config_data = configparser.ConfigParser()
        self.config_data.read(self.ini_path, encoding="utf-8")
        self.title("Python File Commander")
        self.geometry(self.config_data.get("window", "geometry", fallback="1200x720"))
        self.minsize(800, 480)
        self.active: FilePane | None = None
        style = ttk.Style(self)
        style.configure("Active.Treeview", background="white", fieldbackground="white")
        style.map("Active.Treeview", background=[("selected", "#1683e2")], foreground=[("selected", "white")])
        style.configure("Inactive.Treeview", background="white", fieldbackground="white")
        style.map("Inactive.Treeview", background=[("selected", "#91a9bd")], foreground=[("selected", "white")])
        self._build_menu()
        split = ttk.Panedwindow(self, orient="horizontal")
        split.pack(fill="both", expand=True, padx=5, pady=5)
        left_paths = self._saved_paths("left")
        right_paths = self._saved_paths("right")
        self.left_tabs = PaneTabs(split, self.set_active, self.save_config, left_paths)
        self.right_tabs = PaneTabs(split, self.set_active, self.save_config, right_paths)
        self.left = self.left_tabs.current()
        self.right = self.right_tabs.current()
        split.add(self.left_tabs, weight=1)
        split.add(self.right_tabs, weight=1)
        self._restore_tab(self.left_tabs, "left")
        self._restore_tab(self.right_tabs, "right")
        self._restore_panel_options(self.left_tabs, "left")
        self._restore_panel_options(self.right_tabs, "right")
        self.active = self.right_tabs.current() if self.config_data.get("state", "active_panel", fallback="left") == "right" else self.left_tabs.current()
        actions = ttk.Frame(self)
        actions.pack(fill="x", padx=5, pady=(0, 5))
        for text, command in (("F3 Preview", self.preview), ("F4 Search", self.search), ("F5 Copy", self.copy), ("F6 Move", self.move),
                              ("F7 New folder", self.mkdir), ("Del Delete", self.delete), ("F2 Rename", self.rename),
                              ("Ctrl+R Refresh", self.refresh)):
            ttk.Button(actions, text=text, command=command).pack(side="left", fill="x", expand=True, padx=1)
        defaults = {
            "rename": "<F2>", "preview": "<F3>", "search": "<F4>", "copy": "<F5>",
            "move": "<F6>", "new_folder": "<F7>", "delete": "<Delete>", "refresh": "<Control-r>",
            "enter_folder": "<Right>", "parent_folder": "<Left>", "new_tab": "<Control-Up>",
            "close_tab": "<Control-w>", "select_all": "<Control-a>",
            "copy_path": "<Control-Shift-C>", "toggle_hidden": "<Control-h>",
        }
        commands = {
            "rename": self.rename, "preview": self.preview, "search": self.search, "copy": self.copy,
            "move": self.move, "new_folder": self.mkdir, "delete": self.delete, "refresh": self.refresh,
            "enter_folder": self.enter_folder, "parent_folder": self.parent_folder, "new_tab": self.new_tab,
            "close_tab": self.close_tab, "select_all": self.select_all,
            "copy_path": self.copy_path, "toggle_hidden": self.toggle_hidden,
        }
        if not self.config_data.has_section("hotkeys"):
            self.config_data.add_section("hotkeys")
        for name, default in defaults.items():
            key = self.config_data.get("hotkeys", name, fallback=default)
            self.config_data.set("hotkeys", name, key)
            self.bind_all(key, lambda _e, fn=commands[name]: fn())
        self.protocol("WM_DELETE_WINDOW", self.close_app)
        self._ready = True
        self._save_job = None
        self.bind("<Configure>", self._schedule_save)
        self.set_active(self.active)
        self.save_config()

    @staticmethod
    def _find_ini_path() -> Path:
        executable = Path(sys.argv[0]).resolve()
        if executable.name.casefold() == "pfc.py":
            return executable.with_name("pfc.ini")
        return Path(__file__).resolve().parents[1] / "pfc.ini"

    def _saved_paths(self, side: str) -> list[Path]:
        try:
            paths = json.loads(self.config_data.get(side, "tabs", fallback="[]"))
        except (json.JSONDecodeError, TypeError):
            paths = []
        candidates = [Path(value).expanduser() for value in paths]
        valid = [path for path in candidates if path.is_dir()]
        return valid or [Path.home()]

    def _restore_tab(self, tabs: PaneTabs, side: str) -> None:
        index = self.config_data.getint(side, "selected", fallback=0)
        if tabs.tabs():
            tabs.select(tabs.tabs()[min(max(index, 0), len(tabs.tabs()) - 1)])

    def _restore_panel_options(self, tabs: PaneTabs, side: str) -> None:
        column = self.config_data.get(side, "sort_column", fallback="name")
        descending = self.config_data.getboolean(side, "sort_descending", fallback=False)
        show_hidden = self.config_data.getboolean(side, "show_hidden", fallback=True)
        show_system = self.config_data.getboolean(side, "show_system", fallback=True)
        for pane in tabs.panes():
            pane.sort_column = column if column in pane.columns else "name"
            pane.reverse = descending
            pane.show_hidden = show_hidden
            pane.show_system = show_system
            for col in pane.columns:
                marker = (" ▼" if descending else " ▲") if col == pane.sort_column else ""
                pane.tree.heading(col, text=pane.heading_labels[col] + marker)
            pane.refresh()

    def _schedule_save(self, _event=None) -> None:
        if not self._ready:
            return
        if self._save_job is not None:
            self.after_cancel(self._save_job)
        self._save_job = self.after(250, self.save_config)

    def save_config(self) -> None:
        if not self._ready:
            return
        for side, tabs in (("left", self.left_tabs), ("right", self.right_tabs)):
            if not self.config_data.has_section(side):
                self.config_data.add_section(side)
            panes = tabs.panes()
            self.config_data.set(side, "tabs", json.dumps([str(p.path) for p in panes]))
            self.config_data.set(side, "selected", str(tabs.index(tabs.select())))
            current = tabs.current()
            self.config_data.set(side, "sort_column", current.sort_column)
            self.config_data.set(side, "sort_descending", str(current.reverse).lower())
            self.config_data.set(side, "show_hidden", str(current.show_hidden).lower())
            self.config_data.set(side, "show_system", str(current.show_system).lower())
        if not self.config_data.has_section("window"):
            self.config_data.add_section("window")
        if not self.config_data.has_section("state"):
            self.config_data.add_section("state")
        self.config_data.set("window", "geometry", self.geometry())
        self.config_data.set("state", "active_panel", "left" if self.active in self.left_tabs.panes() else "right")
        temporary = self.ini_path.with_suffix(".ini.tmp")
        try:
            with temporary.open("w", encoding="utf-8") as stream:
                self.config_data.write(stream)
            temporary.replace(self.ini_path)
        except OSError:
            pass

    def close_app(self) -> None:
        self.save_config()
        self.destroy()

    def _build_menu(self) -> None:
        menu = tk.Menu(self)
        files = tk.Menu(menu, tearoff=False)
        files.add_command(label="Preview in other panel\tF3", command=self.preview)
        files.add_command(label="Search\tF4", command=self.search)
        files.add_command(label="Rename\tF2", command=self.rename)
        files.add_separator()
        files.add_command(label="Exit", command=self.destroy)
        menu.add_cascade(label="Files", menu=files)
        view = tk.Menu(menu, tearoff=False)
        visibility = tk.Menu(view, tearoff=False)
        self.show_hidden_var = tk.BooleanVar(value=True)
        self.show_system_var = tk.BooleanVar(value=True)
        visibility.add_checkbutton(label="Show Hidden", variable=self.show_hidden_var,
                                   command=self.set_hidden_visibility)
        visibility.add_checkbutton(label="Show System", variable=self.show_system_var,
                                   command=self.set_system_visibility)
        view.add_cascade(label="File Visibility", menu=visibility)
        menu.add_cascade(label="View", menu=view)
        self.config(menu=menu)

    def set_active(self, pane: FilePane) -> None:
        self.active = pane
        self.show_hidden_var.set(pane.show_hidden)
        self.show_system_var.set(pane.show_system)
        if hasattr(self, "left_tabs"):
            for candidate in self.left_tabs.panes() + self.right_tabs.panes():
                candidate.set_active_appearance(candidate is pane)
        self.save_config()

    def panes(self) -> tuple[FilePane, FilePane]:
        source = self.active or self.left_tabs.current()
        left_panes = [self.left_tabs.nametowidget(tab) for tab in self.left_tabs.tabs()]
        return (source, self.right_tabs.current() if source in left_panes else self.left_tabs.current())

    def refresh(self) -> None:
        self.left_tabs.current().refresh(); self.right_tabs.current().refresh()

    def open(self) -> None:
        self.panes()[0].open_selected()

    def enter_folder(self) -> None:
        self.open()

    def parent_folder(self) -> None:
        self.panes()[0].up()

    def preview(self) -> None:
        source, target = self.panes()
        items = source.selected_paths()
        if items:
            target.show_preview(items[0])

    def search(self) -> None:
        source, _ = self.panes()
        query = simpledialog.askstring("Search", "File or folder name contains:", parent=self)
        if query:
            source.search(query)

    def new_tab(self) -> None:
        source, _ = self.panes()
        tabs = self.left_tabs if source in [self.left_tabs.nametowidget(t) for t in self.left_tabs.tabs()] else self.right_tabs
        self.active = tabs.add_tab(source.path)

    def close_tab(self) -> None:
        source, _ = self.panes()
        tabs = self.left_tabs if source in [self.left_tabs.nametowidget(t) for t in self.left_tabs.tabs()] else self.right_tabs
        tabs.close_current()
        self.active = tabs.current()

    def select_all(self) -> None:
        source, _ = self.panes()
        source.tree.selection_set(source.tree.get_children())

    def copy_path(self) -> None:
        source, _ = self.panes()
        items = source.selected_paths()
        value = str(items[0] if items else source.path)
        self.clipboard_clear(); self.clipboard_append(value)

    def toggle_hidden(self) -> None:
        source = self.panes()[0]
        source.toggle_hidden()
        self.show_hidden_var.set(source.show_hidden)

    def set_hidden_visibility(self) -> None:
        source = self.panes()[0]
        source.show_hidden = self.show_hidden_var.get()
        source.refresh(); source.on_change()

    def set_system_visibility(self) -> None:
        source = self.panes()[0]
        source.show_system = self.show_system_var.get()
        source.refresh(); source.on_change()

    def _run(self, verb: str, operation) -> None:
        source, target = self.panes()
        items = source.selected_paths()
        if not items:
            return
        if not messagebox.askyesno(verb, f"{verb} {len(items)} selected item(s) to:\n{target.path}?"):
            return
        try:
            operation(items, target.path)
            self.refresh()
        except OSError as exc:
            messagebox.showerror(f"{verb} failed", str(exc))

    def copy(self) -> None:
        self._run("Copy", copy_items)

    def move(self) -> None:
        self._run("Move", move_items)

    def delete(self) -> None:
        source, _ = self.panes()
        items = source.selected_paths()
        if items and messagebox.askyesno("Permanent delete", f"Permanently delete {len(items)} selected item(s)?"):
            try:
                delete_items(items); self.refresh()
            except OSError as exc:
                messagebox.showerror("Delete failed", str(exc))

    def mkdir(self) -> None:
        source, _ = self.panes()
        name = simpledialog.askstring("New folder", "Folder name:", parent=self)
        if name:
            try:
                (source.path / name).mkdir(); source.refresh()
            except OSError as exc:
                messagebox.showerror("Create failed", str(exc))

    def rename(self) -> None:
        source, _ = self.panes()
        items = source.selected_paths()
        if len(items) != 1:
            messagebox.showinfo("Rename", "Select exactly one item."); return
        name = simpledialog.askstring("Rename", "New name:", initialvalue=items[0].name, parent=self)
        if name and name != items[0].name:
            try:
                items[0].rename(items[0].with_name(name)); self.refresh()
            except OSError as exc:
                messagebox.showerror("Rename failed", str(exc))


def main() -> None:
    Commander().mainloop()


if __name__ == "__main__":
    main()
