"""Build the portable single-file edition from the maintainable package sources."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def build() -> Path:
    fileops = (ROOT / "pycommander" / "fileops.py").read_text(encoding="utf-8")
    icons = (ROOT / "pycommander" / "icons.py").read_text(encoding="utf-8")
    app = (ROOT / "pycommander" / "app.py").read_text(encoding="utf-8")

    fileops = fileops.replace("from __future__ import annotations\n\n", "", 1)
    icons = icons.replace("from __future__ import annotations\n\n", "", 1)
    app = app.replace("from __future__ import annotations\n\n", "", 1)
    app = "\n".join(line for line in app.splitlines() if not line.startswith("from .")) + "\n"
    banner = '''"""Portable Python File Commander.

Generated from the pycommander package. Requires only Python 3.10+ with Tk.
Do not edit this file directly; run tools/build_single_file.py after source changes.
"""

from __future__ import annotations

'''
    output = ROOT / "pfc.py"
    output.write_text(banner + fileops + "\n\n" + icons + "\n\n" + app + "\n\nif __name__ == \"__main__\":\n    main()\n", encoding="utf-8")
    return output


if __name__ == "__main__":
    print(build())
