"""Build the portable edition from one ordered, reviewable module manifest."""
import ast
from datetime import datetime
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
# Keep definition order: some class bases/defaults are evaluated during import.
# Runtime-only references may deliberately point to a later module.
MODULES = (
    "i18n", "fileops", "clipboard", "icons", "startup", "dirwatch", "vcs",
    "tabicons", "tabs", "tooltip", "columnsettings", "pathbar", "homeprefix",
    "cloudstatus", "marquee", "detailcells", "singlepanel", "windowplacement",
    "settingsshots", "workflowdata", "debuglog", "dialogs", "workflows",
    "workspaces", "syncprogress", "settingspreview", "settings", "vcsactions",
    "actionbar", "vcsui", "comparecolors", "reviewcore", "reviewstorage",
    "workbook", "reviewjobs", "reviewui", "workbookui", "archivereview",
    "archivereviewui", "textio", "compare", "mdworkspace", "mdworkspaceui",
    "mdlinks", "mdjobs", "markdownblocks", "preview", "search", "multirename",
    "archivefs", "spaceanalyzer", "shelldnd", "shellmenu", "app",
)
BANNER = '''"""Portable Python File Commander.

Generated from the pycommander package. Requires only Python 3.10+ with Tk.
Do not edit this file directly; run tools/build_single_file.py after source changes.
"""

from __future__ import annotations

'''


def flatten_source(source: str, filename: str) -> str:
    """Remove only top-level package/future imports, including multiline ones.

    Indented fallback imports and strings/comments are not textual matches.
    Aliases are unsafe in a shared namespace; fail rather than discard them.
    """
    lines = source.splitlines(keepends=True)
    for node in ast.parse(source, filename=filename).body:
        if not isinstance(node, ast.ImportFrom):
            continue
        if not node.level and node.module != "__future__":
            continue
        if node.level and (node.level != 1 or any(a.asname or a.name == "*" for a in node.names)):
            raise ValueError(f"{filename}:{node.lineno}: unsupported portable import")
        if not node.level and any(a.name != "annotations" for a in node.names):
            raise ValueError(f"{filename}:{node.lineno}: unsupported future import")
        # Removing an import must not remove another statement on the same line.
        suffix = lines[node.end_lineno - 1].encode("utf-8")[node.end_col_offset:].strip()
        if node.col_offset or suffix.startswith(b";"):
            raise ValueError(f"{filename}:{node.lineno}: import must occupy its own lines")
        for index in range(node.lineno - 1, node.end_lineno):
            lines[index] = "\n"
    return "".join(lines).rstrip() + "\n"


def render(root: Path = ROOT, build_date: str | None = None) -> str:
    package = (root / "pycommander" / "__init__.py").read_text(encoding="utf-8")
    version = re.search(r'^__version__\s*=\s*["\']([^"\']+)["\']', package, re.MULTILINE)
    if version is None:
        raise RuntimeError("pycommander.__version__ is missing")
    fragments = []
    for module in MODULES:
        path = root / "pycommander" / (module + ".py")
        source = path.read_text(encoding="utf-8")
        if module == "app":
            substitutions = {
                "from . import __version__": f'__version__ = "{version.group(1)}"',
                'BUILD_DATE = datetime.now().strftime("%Y/%m/%d")':
                    f'BUILD_DATE = "{build_date or datetime.now().strftime("%Y/%m/%d")}"',
            }
            for before, after in substitutions.items():
                if source.count(before) != 1:
                    raise RuntimeError(f"Portable app substitution missing or ambiguous: {before}")
                source = source.replace(before, after, 1)
        fragments.append(f"# Source: pycommander/{module}.py\n" + flatten_source(source, str(path)))
    result = BANNER + "\n\n".join(fragments) + '\n\nif __name__ == "__main__":\n    main()\n'
    compile(result, "pfc.py", "exec")  # Validate before replacing the usable artifact.
    return result


def build() -> Path:
    output = ROOT / "pfc.py"
    output.write_text(render(), encoding="utf-8")
    return output


if __name__ == "__main__":
    print(build())
