"""Build the portable single-file edition from the maintainable package sources."""

from datetime import datetime
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def build() -> Path:
    fileops = (ROOT / "pycommander" / "fileops.py").read_text(encoding="utf-8")
    clipboard = (ROOT / "pycommander" / "clipboard.py").read_text(encoding="utf-8")
    icons = (ROOT / "pycommander" / "icons.py").read_text(encoding="utf-8")
    tabs = (ROOT / "pycommander" / "tabs.py").read_text(encoding="utf-8")
    tooltip = (ROOT / "pycommander" / "tooltip.py").read_text(encoding="utf-8")
    compare = (ROOT / "pycommander" / "compare.py").read_text(encoding="utf-8")
    preview = (ROOT / "pycommander" / "preview.py").read_text(encoding="utf-8")
    search = (ROOT / "pycommander" / "search.py").read_text(encoding="utf-8")
    app = (ROOT / "pycommander" / "app.py").read_text(encoding="utf-8")
    build_date = datetime.now().strftime("%Y/%m/%d")
    app = app.replace('BUILD_DATE = datetime.now().strftime("%Y/%m/%d")',
                      f'BUILD_DATE = "{build_date}"', 1)

    fileops = fileops.replace("from __future__ import annotations\n\n", "", 1)
    clipboard = clipboard.replace("from __future__ import annotations\n\n", "", 1)
    icons = icons.replace("from __future__ import annotations\n\n", "", 1)
    tabs = tabs.replace("from __future__ import annotations\n\n", "", 1)
    tooltip = tooltip.replace("from __future__ import annotations\n\n", "", 1)
    compare = compare.replace("from __future__ import annotations\n\n", "", 1)
    compare = "\n".join(line for line in compare.splitlines() if not line.startswith("from .")) + "\n"
    preview = preview.replace("from __future__ import annotations\n\n", "", 1)
    preview = "\n".join(line for line in preview.splitlines() if not line.startswith("from .")) + "\n"
    search = search.replace("from __future__ import annotations\n\n", "", 1)
    search = "\n".join(line for line in search.splitlines() if not line.startswith("from .")) + "\n"
    app = app.replace("from __future__ import annotations\n\n", "", 1)
    app = "\n".join(line for line in app.splitlines() if not line.startswith("from .")) + "\n"
    banner = '''"""Portable Python File Commander.

Generated from the pycommander package. Requires only Python 3.10+ with Tk.
Do not edit this file directly; run tools/build_single_file.py after source changes.
"""

from __future__ import annotations

'''
    output = ROOT / "pfc.py"
    output.write_text(banner + fileops + "\n\n" + clipboard + "\n\n" + icons + "\n\n" + tabs + "\n\n" + tooltip + "\n\n" + compare + "\n\n" + preview + "\n\n" + search + "\n\n" + app + "\n\nif __name__ == \"__main__\":\n    main()\n", encoding="utf-8")
    return output


if __name__ == "__main__":
    print(build())
